#!/usr/bin/env bash
#
# USAGE
#
#     ./rcp.sh <dst>
#
# DESCRIPTION
#
#     Copies a directory from source to destination using rsync's
#     include/exclude features.
#
# NOTE
#
#     This template must be used from within the source directory.
#
#     A trailing slash on the source path copies the contents of the source
#     directory rather than the directory itself.
#
# INCLUDE/EXCLUDE MATCHING
#
#     Patterns starting with '/' are anchored to a particular spot in the
#     directory tree hierarchy.
#
#     Patterns ending with '/' only match directories.
#
# EXAMPLES
#
#     '- *.o' excludes all matching names
#
#     '- /foo' excludes the matching name in the transfer-root directory
#
#     '- foo/' excludes all matching directories
#
#     '+ foo/ + foo/bar.c - *' includes only foo/ and and foo/bar.c
#

rsync -av - /.git - /resources ../<dirname>/ $1
