#!/usr/bin/env python3
"""
Usage:
    hexaddr [-b <size>] [-n <count>] [-s <start>]

Compute a range of hex addresses.

Options:
    -s <start>
        Start address.

    -b <size>
        Bytes per address. Defaults to 4.

    -n <count>
        Number of permutation to print. Default: 8.
"""
from docopt import docopt

from math import log, floor

def main():
    argv = docopt(__doc__, help=True)

    start = 0
    if argv["-s"]:
        start = int(argv["-s"])
    start = max(0, start)

    count = 8
    if argv["-n"]:
        count = int(argv["-n"])
    count = max(1, count)

    nbytes = 4
    if argv["-b"]:
        nbytes = int(argv["-b"])
    nbytes = max(1, nbytes)

    maxval = nbytes * (count - 1)
    maxdigits = floor(log(maxval, 16)) + 1
    fstring = "0x{:0" + str(maxdigits) + "X}"

    for i in range(count):
        val = start + i * nbytes
        print(fstring.format(val))

main()
