#!/usr/bin/env python3
"""
Usage:
    hexaddr [-b <size>] [-n <count>]

Options:
    --help
        Print this menu.

    -b <size>
        Word size in bytes. Default 4. Possible values: 1, 2, 4, 8, 16.

    -n <count>
        Number of permutation to print. Default: 8.
"""
from docopt import docopt

def main():
    argv = docopt(__doc__, help=True)

    size = 4
    count = 8

    if argv["-n"]:
        count = int(argv["-n"])

    if argv["-b"]:
        size = int(argv["-b"])

    if size not in [1, 2, 4, 8, 16]:
        print("ERROR: Invalid size '{}'".format(size))
        exit(1)

    if count < 0:
        print("ERROR: Invalid count '{}'".format (count))
        exit(1)

    for i in range(count):
        val = i * size
        print("0x{:012X}".format(val))

main()
