#!/usr/bin/env python3

import sys
import re

# Expected format:
#
# 0x0 <string 1>
# 0x4 <string 2>
# 0x8 <string 4>

def get_vals(line):
    capt = re.match(r"(0x.*) (.*)", line)
    assert capt != None, \
        'Failed to parse line'
    return int(capt.group(1), 16), capt.group(2)

def main():
    bytes_per_addr = 4

    index = 0

    buff = sys.stdin.read().splitlines()

    for i in range(len(buff) - 1):
        line0 = buff[i]
        line1 = buff[i + 1]

        addr0, string0 = get_vals(line0)
        addr1, string1 = get_vals(line1)

        assert ((addr1 - addr0) % bytes_per_addr) == 0, \
            f'Address difference not multiple of {bytes_per_addr}'

        diff = int(((addr1 - addr0) - bytes_per_addr) / bytes_per_addr)

        if diff != 0:
            print('u32 RESERVED{}[{}];'.format(index, diff))
            index += 1

        if i == 0:
            print('u32 {};'.format(string0))

        print('u32 {};'.format(string1))

if __name__ == '__main__':
    main()
