#!/usr/bin/env python3
"""
Usage:
    hexdiff <file_path> [-x <x>] [-y <y>]

Create a memory map from a sequence of hex addresses.

Options:
    <file_path>
        Target file.

    -x <x>
        Address column. [default: 0]

    -y <y>
        Name column. [default: 1]
"""
import sys
import re
import os

from docopt import docopt


class Option:
    X = 0
    Y = 1


def get_vals(line):
    line = line.split(' ')

    if len(line) < 2:
        print('Error: Invalid line format')
        exit(1)

    addr, name = line[Option.X], line[Option.Y]

    if not addr.startswith('0x'):
        print('Error: Invalid address format')
        exit(1)

    return int(addr, 16), name


def read_file(path):
    if not os.path.isfile(path):
        print('Error: Invalid path')
        exit(1)

    with open(path, 'r') as fh:
        return fh.read().strip().splitlines()


def create_diff_map(buff):
    bytes_per_addr = 4
    index = 0  # Index for RESERVED register

    for i in range(len(buff) - 1):
        line0 = buff[i]
        line1 = buff[i + 1]

        addr0, name0 = get_vals(line0)
        addr1, name1 = get_vals(line1)

        if ((addr1 - addr0) % bytes_per_addr) != 0:
            print(f'Error: Address not multiple of {bytes_per_addr}')
            exit(1)

        diff = int(((addr1 - addr0) - bytes_per_addr) / bytes_per_addr)

        if diff != 0:
            print('u32 RESERVED{}[{}];'.format(index, diff))
            index += 1

        if i == 0:
            print('u32 {};'.format(name0))

        print('u32 {};'.format(name1))


def main():
    argv = docopt(__doc__, help=True)

    Option.X = int(argv['-x'])
    Option.Y = int(argv['-y'])

    buff = read_file(argv['<file_path>'])

    create_diff_map(buff)


if __name__ == '__main__':
    main()
