#!/usr/bin/env python3
"""
Usage:
    hexmem <value>

Compute the base-2 memory size from a given value.

Options:
    <value>
        The value, in bytes, to convert.
"""
from docopt import docopt

from math import log, ceil

argv = docopt(__doc__, help=True)

val = int(argv['<value>'])
val = max(1, val)
exp = ceil(log(val, 2))
val = 2**exp
print(hex(val), val)
