#!/usr/bin/env python3
"""
Usage:
    hexmem <value>

Compute the base-2 memory size from a given value.

Options:
    <value>
        The value, in bytes, to convert. Accepted formats are decimal and hexadecimal.
"""
import re

from docopt import docopt
from math import log, ceil


def parse_value(value):
    capt = re.match(r'0x[A-Za-z0-9]', value)
    if not capt:
        return int(value)
    return int(value, 16)


argv = docopt(__doc__, help=True)

val = parse_value(argv['<value>'])  # int(argv['<value>'])
val = max(1, val)
exp = ceil(log(val, 2))
val = 2**exp

print(hex(val), val)
