#!/usr/bin/env python3
"""
Usage:
    hexmask [-n <count>]

Compute a hexmask range.

Options:
    --help
        Print this menu.

    -n <count>
        Number of permutations to print. Default: 8.
"""
from docopt import docopt

from math import log, floor

def main():
    argv = docopt(__doc__, help=True)

    count = 8

    if argv["-n"]:
        count = int(argv["-n"])

    count = max(1, count)

    maxval = 1 << (count - 1)
    maxdigits = floor(log(maxval, 16)) + 1
    fstring = "0x{:0" + str(maxdigits) + "X}"

    for i in range(count):
        print(fstring.format(1 << i))

main()
