#!/usr/bin/env python3
"""
Usage:
    ipsn <serial_number>

Options:
    --help
        Print this menu.

    <serial_number>
        Serial number of the device.
"""

from docopt import docopt

def main():
    argv = docopt(__doc__, help=True)

    snr = int(argv["<serial_number>"])

    A = int(snr / 256) + 100
    B = int(snr % 256)

    print(f"10.19.{A}.{B}")

if __name__ == '__main__':
    main()
