#!/usr/bin/env python3
#
# DESCRIPTION
#
#     Displays information about the current date
#

import datetime

day_name = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
)

if __name__ == "__main__":
    date = datetime.datetime.now().strftime("%Y-%m-%d")
    time = datetime.datetime.now().strftime("%H:%M:%S")
    _, week, dow = datetime.date.today().isocalendar()

    print(
        "Week {week} {dow} {date} {time}".format(
            date = date, time = time, week = week, dow = day_name[dow - 1])
    )
