#!/usr/bin/env python3
#
# SYNTAX
#
#     palign <symbol>
#
# OPTIONS
#
#     symbol
#
#         Quoted alignment symbol.
#
# DESCRIPTION
#
#     Aligns a block of text by the first occurrence of the alignment symbol.
#
#     Reads from stdin and writes to stout.
#
# EXAMPLE
#
#     $ cat << EOF | palign "="
#     > a = b
#     > aa = b
#     > a = b
#     > aaa = b
#     > EOF
#
#     a   = b
#     aa  = b
#     a   = b
#     aaa = b
#

import sys

token = None
max_size = None

if __name__ == "__main__":
    argv = sys.argv[1:]

    if len(argv) == 0:
        print("[ERROR] No alignment symbol provided")
        quit(1)

    token = argv[0]
    stdin = sys.stdin.read().rstrip().split("\n")
    lhs = list(map(lambda x: x.split(token, 1)[0].rstrip(), stdin))
    max_size = len(max(lhs, key=len))

    for line in stdin:
        lhs, rhs = line.split(token, 1)
        lhs = lhs.rstrip()
        rhs = rhs.lstrip()
        alpha = max_size - len(lhs)
        beta = 1
        print(lhs + " " * (alpha + beta) + token + (" " * beta) + rhs)
