#!/usr/bin/env python3
#
# SYNTAX
#
#     pargs <program>
#
# DESCRIPTION
#
#     Calls program with the arguments provided by stdin.
#
# EXAMPLE
#
#     $ echo "foo bar bas" | tr ' ' '\n' |  pargs echo
#
#     foo
#     bar
#     bas
#

import sys
import subprocess

if __name__ == "__main__":
    stdin = sys.stdin.read().lstrip().split("\n")

    argv = sys.argv[1:]

    if len(stdin) == 0:
        print("[ERROR] No input detected")
        quit(1)

    if len(argv) == 0:
        print("[ERROR] Missing arguments")
        quit(1)

    # Prune empty strings
    stdin = [ x for x in stdin if len(x) > 0 ]

    program = argv[0]

    for arg in stdin:
        try:
            subprocess.call("{} {}".format(program, arg), shell=True)
        except:
            print("[ERROR] Failed to execute command: {}".format(command))
