#!/usr/bin/env python3
#
# SYNTAX
#
#     pbreak <symbol>
#
# OPTIONS
#
#     symbol
#
#         The symbol at which to break the string.
#
# DESCRIPTION
#
#    Inserts a newline after each occurrence of the target symbol and indents
#    all lines accordingly.
#
#    Reads from stdin and writes to stdout.
#
# EXAMPLE
#
#     $ echo "a: b: c: d:" | pbreak ":"
#
#     a:
#     b:
#     c:
#     d:
#

import sys
import re

if __name__ == "__main__":
    argv = sys.argv[1:]

    if len(argv) != 1:
        print("[ERROR] Missing break symbol")
        quit(1)

    token = argv[0]

    stdin = sys.stdin.read().rstrip().split(token)
    for i in range(len(stdin) - 1):
        stdin[i] = stdin[i] + token

    indent = len(stdin[0]) - len(stdin[0].lstrip())

    print(stdin[0])
    for line in stdin[1:]:
        print(" " * (indent) + line.lstrip())
