#!/usr/bin/env python3
#
# DESCRIPTION
#
#     Displays all months and days in the current year
#

from datetime import datetime
import calendar

monthname = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)

cyear = datetime.now().year
cmonth = datetime.now().month
cday = datetime.now().day

def weekday(y, m, d):
    return datetime(y, m, d).isocalendar()[1]

def print_sequential():
    print(cyear, end="\n\n")
    dseq = [ calendar.monthrange(cyear, x)[1] for x in range(1, 12 + 1) ]
    for month, ndays in enumerate(dseq, 1):
        print(monthname[month - 1])
        print("-" * 33)
        for day in range(1, ndays + 1):
            if month == cmonth and day == cday:
                print("[{:2}]".format(day), end=" ")
            else:
                print(" {:2} ".format(day), end=" ")
            if day % 7 == 0:
                print()
        print()
        if ndays % 7 != 0:
            print()

print_sequential()
