#!/usr/bin/env python3
"""
Usage:
    pcal [<year> | --month]

Options:
    -h, --help
        Print this menu.

    <year>
        Print the calendar year for the specified year. Defaults to the current year.

    -m, --month
        Print the calendar month for the current month.
"""

import calendar

from datetime import datetime
from docopt import docopt

# 1-base indexed month names
monthname = [
    None, "January", "February", "March", "April", "May", "June", "July",
    "August", "September", "October", "November", "December" ]

# Current year, month, day
cyear  = datetime.now().year
cmonth = datetime.now().month
cday   = datetime.now().day

FORMAT_DAY   = "{:3}"
FORMAT_CDAY  = "\x1b[45m{:3}\x1b[0m"
FORMAT_WEEK  = "\x1b[95m{:3}\x1b[0m"
FORMAT_MONTH = "\x1b[95m{}\x1b[0m"

def is_today(y, m, d):
    return (y == cyear) and (m == cmonth) and (d == cday)

def print_day(y, m, d):
    if not is_today(y, m, d):
        print(FORMAT_DAY.format(d), end=" ")
    else:
        print(FORMAT_CDAY.format(d), end=" ")

def print_week(y, m, d):
    print((FORMAT_WEEK + " | ").format(datetime(y, m, d).isocalendar().week), end="")

def print_month(m):
    print(FORMAT_MONTH.format(monthname[m]), end=" ")

def print_calendar_year(y):
    print_calendar_month(y, 1)
    for m in range(2, 13):
        print_calendar_month(y, m, chain=True)

def print_calendar_month(y, m, chain=False):
    dow, days = calendar.monthrange(y, m)

    # Only print week number if not chained or if day of the week is zero,
    # i.e. the first day of the week.
    if not chain or dow == 0:
        print_week(y, m, 1)
        for _ in range(dow):
            print(FORMAT_DAY.format(""), end=" ")

    start_of_week  = False
    start_of_month = True

    for d in range(1, days + 1):
        if start_of_week:
            print_week(y, m, d)
            start_of_week = False

        print_day(y, m, d)

        dow = (dow + 1) % 7

        if dow == 0:
            if start_of_month:
                print_month(m)
                start_of_month = False
            print()
            start_of_week = True

if __name__ == "__main__":
    argv = docopt(__doc__, help=True)

    if argv["<year>"]:
        year = int(argv["<year>"])
        print_calendar_year(year)
        print()
        exit(0)

    if argv["--month"]:
        print_calendar_month(cyear, cmonth)
        print()
        exit(0)

    print_calendar_year(cyear)
    print()
