#!/usr/bin/env python3
#
# DESCRIPTION
#
#     Prints terminal colours.
#

def print_color_table():
    for style in range(8):
        for fg in range(30, 38):
            s = ''
            for bg in range(40, 48):
                cc = ';'.join([str(style), str(fg), str(bg)])
                s += '\x1b[{}m {} \x1b[0m'.format(cc, cc)
            print(s)
        print('\n')

if __name__ == "__main__":
    print_color_table()
