#!/usr/bin/env python3

import json
import sys
import ast

def format_string(s):
    try:
        prettystring = json.loads(s)
        return prettystring
    except:
        pass
    try:
        prettystring = ast.literal_eval(s)
        return prettystring
    except:
        pass

    return None

if __name__ == "__main__":
    s = sys.stdin.read()

    prettystring = None
    try:
        prettystring = format_string(s) 
        prettystring = json.dumps(prettystring, indent = 4, sort_keys = True)
    except:
        print("[ERROR] Failed to parse string")
        quit(1)

    print(prettystring)
