#!/usr/bin/env python3

import re

from serial.tools.list_ports import comports

class VID:
    xilinx = 1027

def get_com_ports(vid):
    com_ports =  [ x.device for x in comports() if x.vid == vid ]
    return sorted(com_ports, key=lambda x: int(re.search(r"\d+", x).group(0)))

def print_com_ports(vid):
    com_ports = get_com_ports(vid)
    for item in com_ports:
        print(item)

if __name__ == '__main__':
    print_com_ports(VID.xilinx)
