#!/usr/bin/env python3
#
# DESCRIPTION
#
#     Displays information about a day in the future
#

import sys

from datetime import datetime
from dateutil.relativedelta import relativedelta as delta

day_name = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
)

def ymd_diff(date):
    diff       = delta(date, datetime.now())
    years      = diff.years
    months     = diff.months
    days       = diff.days
    days_total = (date - datetime.now()).days

    return "{} years {} months {} days | {} days total".format(
        years, months, days, days_total)

if __name__ == "__main__":
    argv = sys.argv[1:]

    if len(argv) == 0:
        print("[ERROR] Missing target date (yyyy-mm-dd)")
        quit(1)

    date = None

    try:
        date = datetime.strptime(argv[0], "%Y-%m-%d")
    except:
        print("[ERROR] Date must be ISO (yyyy-mm-dd)")
        quit(1)

    _, week, dow = date.isocalendar()

    diff = ymd_diff(date)

    print(
        "Week {week} {dow} {date} | {diff}".format(
            date = date.strftime("%Y-%m-%d"),
            week = week,
            dow = day_name[dow - 1],
            diff = diff
        )
    )
