#!/usr/bin/env perl
#
# git-diff-conflicts
#
# DESCRIPTION
#
#     Prints conflicting files.
#

use warnings;
use strict;

if (!`git rev-parse --is-inside-work-tree 2>/dev/null`)
{
    print("[ERROR] Not inside a git environment\n");
    exit 1;
}

print(`git diff --name-only --diff-filter=U`);
