#!/usr/bin/env perl
#
# git-diff-branches <basebranch>
#
# DESCRIPTION
#
#     Prints the number of commits behind/ahead 'basebranch' for all branches in
#     refs/heads.
#

use warnings;
use strict;

use List::Util qw(reduce);

if (!`git rev-parse --is-inside-work-tree 2>/dev/null`)
{
    print("[ERROR] Not inside a git environment\n");
    exit 1;
}

my $argc = scalar @ARGV;

if ($argc == 0)
{
    printf("[ERROR] Target branch cannot be empty\n");
    exit 1;
}

my $branch = $ARGV[0];

print("$branch\n");
print(`git shortlog -s -n --no-merges $branch`);
