#!/usr/bin/env perl
#
# git-diff-branches <basebranch>
#
# DESCRIPTION
#
#     Prints the number of commits behind/ahead 'basebranch' for all branches in
#     refs/heads.
#

use warnings;
use strict;

use List::Util qw(reduce);

if (!`git rev-parse --is-inside-work-tree 2>/dev/null`)
{
    print("[ERROR] Not inside a git environment\n");
    exit 1;
}

my @locals = sort split(/\n/,
    `git for-each-ref --format="%(refname:short)" refs/heads`);

foreach my $branch (@locals)
{
    print("$branch\n");
    print(`git shortlog -s -n --no-merges $branch`);
}
