#!/usr/bin/env perl

use warnings;
use strict;

if (!`git rev-parse --is-inside-work-tree 2>/dev/null`)
{
    print("[ERROR] Not inside a git environment\n");
    exit 1;
}

my $argc = scalar @ARGV;

if ($argc == 0)
{
    printf("[ERROR] Search pattern cannot be empty\n");
    exit 1;
}

my $pattern = $ARGV[0];
my @branches = "";

if ($argc == 2)
{
    my $arg = $ARGV[1];

    if ($arg eq "-r")
    {
        @branches = sort split(/\n/, `git branch -a | egrep "^\\s+remotes" | egrep "$pattern"`);
    }
    elsif ($arg eq "-a")
    {
        @branches = sort split(/\n/, `git branch -a | egrep "$pattern"`);
    }
}
else
{
    @branches = sort split(/\n/, `git branch | egrep "$pattern"`);
}

foreach my $branch (@branches)
{
    $branch =~ s/^\s+//g;
    my @items = split("/", $branch);
    if (scalar @items > 2)
    {
        if (index($items[2], "HEAD ->") == -1)
        {
            printf("[${items[1]}] ${items[-1]}\n");
        }
    }
    else
    {
        printf("$branch\n");
    }
}
