#!/usr/bin/env bash

fun::print_usage()
{
cat << EOF
Usage:
    cat-ssh <public key> <host>

Options:
    <public key>
        Path to the public key to upload.

    <host>
        Target host.
EOF
}

[[ "$#" -ne 2 ]] && fun::print_usage && exit 1

cat "$1" | ssh "$2" "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
