#!/usr/bin/env bash

set -e

fun::exit()
{
    echo "Usage: git-fetch-github-pr <origin> <request_id>"
    exit 1
}

[[ "$#" -ne 2 ]] && fun::exit

SOURCE="+refs/pull/$2/head"
TARGET="refs/remotes/$1/pr/$2"

git fetch "$1" "$SOURCE:$TARGET" && git checkout pr/$2
