#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "Usage: git-fetch-bitbucket-pr <origin> <prnumber>"
    exit 1
fi

git fetch "$1" "+refs/pull-requests/$2/from:refs/remotes/$1/pr/$2"

if [ $? -eq 0 ]; then
    echo "Fetched pr/$2 from $1"
else
    echo "[ERROR] Failed to fetch pr/$2 from $1"
fi
