#!/usr/bin/env bash
#
# pdf2png <target>
#
# DESCRIPTION
#
#     Converts the target PDF file to PNG using Cairo. A separate PNG file is
#     created for every PDF page.
#

pdftocairo -r 500 -png "$1" "${1%.*}"
