#!/usr/bin/env bash
#
# pdf2range <target> <first page> <last page>
#
# DESCRIPTION
#
#     Extracts the specified range (including) into a new PDF file using Cairo.
#

pdftocairo -r 500 -pdf -f "$2" -l "$3" "$1" "${1%.*}-out.pdf"
