#!/usr/bin/env bash
#
# pdf2png <file>
#
# DESCRIPTION
#
#     Converts the first page in 'file' to png with the same name.
#

file=$(basename -- "$1")
outname=${file%.*}
pdftoppm $file $outname -png -singlefile -r 300
