#!/usr/bin/env bash
#
# pdfsplit <file>
#
# DESCRIPTION
#
#     Splits each page in 'file' into a separate pdf file.
#

file=$(basename -- "$1")
outname=${file%.*}
qpdf --split-pages $file "${outname}_%d.pdf"
