#!/usr/bin/env bash
#
# USAGE
#
#     ./rcp.sh <src> <dst>
#
# NOTE
#
#     'src' must be quoted if it represents more than one file or a file
#     pattern.
#

rsync -av -e ssh \
    --exclude='*.git' \
    $1 $2
