#!/usr/bin/env bash

arg_print_usage()
{
    cat << EOF
Usage:
    sshkey-upload <public key> <host>
EOF
}

[[ "$#" -ne 2 ]] && arg_print_usage && exit 1

cat "$1" | ssh "$2" "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
